name: Sync Main to opencep.com

on:
  schedule:
    - cron: '0 */3 * * *'

  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Sync branches
        run: |
          git checkout opencep.com
          git merge main --no-ff
          git push origin opencep.com
